version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./config.yml:/app/config.yml:ro
    environment:
      - FLASK_ENV=production
      - SITE_URL=${SITE_URL:-http://localhost:5000}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s